{% set name = "lume-gpt" %}
{% set version = "1.0.10" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ColwynGulliford/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: f53680cfa6b4cc6860b7a8b692738f0db53da7ccad84853c97749b2d949cb168


build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - setuptools
    - pip
  run:
    - python >=3.9
    - h5py
    - matplotlib-base
    - numpy
    - scipy >=1.0.0
    - openpmd-beamphysics>=0.14.0
    - pyyaml
    - distgen
    - easygdf

test:
  imports:
    - gpt

about:
  home: https://github.com/ColwynGulliford/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: LUME-GPT
  description: |
    LUME GPT

extra:
  recipe-maintainers:
    - ColwynGulliford
