{% set name = "lume-gpt" %}
{% set version = "1.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ColwynGulliford/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 958b6ff773800506203f4c06f108a6ef640069cd9a6d5b63ece64ebe245cf277

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - setuptools
    - pip
  run:
    - python >=3.9
    - h5py
    - matplotlib-base
    - numpy
    - scipy >=1.0.0
    - openpmd-beamphysics
    - pyyaml
    - distgen
    - easygdf

test:
  imports:
    - gpt

about:
  home: https://github.com/ColwynGulliford/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: LUME-GPT
  description: |
    LUME GPT

extra:
  recipe-maintainers:
    - ColwynGulliford
