{% set name = "lume-gpt" %}
{% set version = "1.0.11" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ColwynGulliford/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 77722c27dde9d8a51c6c508439ed1112b1e4075253794c2bb3e3451ecbb4f1a5


build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python >=3.9
    - setuptools
    - pip
  run:
    - python >=3.9
    - h5py
    - matplotlib-base
    - numpy
    - scipy >=1.0.0
    - openpmd-beamphysics>=0.14.0
    - pyyaml
    - distgen
    - easygdf

test:
  imports:
    - gpt

about:
  home: https://github.com/ColwynGulliford/{{ name }}
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE
  summary: LUME-GPT
  description: |
    LUME GPT

extra:
  recipe-maintainers:
    - ColwynGulliford
